<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>963f7e03-f0fb-4fa8-b89f-ad5d20f6204f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetArchitecture.Application\DotnetArchitecture.Application.csproj" />
    <ProjectReference Include="..\DotnetArchitecture.Persistence\DotnetArchitecture.Persistence.csproj" />
  </ItemGroup>

</Project>
